<script src="<?php echo assets_url('assets_2/js/vendor/jquery-library.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/vendor/bootstrap.min.js'); ?>"></script>
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCR-KEWAVCn52mSdeVeTqZjtqbmVJyfSus&amp;language=en"></script>
<script src="<?php echo assets_url('assets_2/js/tinymce/tinymce.min4bb5.js?apiKey=4cuu2crphif3fuls3yb1pe4qrun9pkq99vltezv2lv6sogci'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/responsivethumbnailgallery.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/jquery.flagstrap.min.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/backgroundstretch.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/owl.carousel.min.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/jquery.vide.min.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/jquery.collapse.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/scrollbar.min.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/chartist.min.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/prettyPhoto.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/jquery-ui.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/countTo.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/appear.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/gmap3.js'); ?>"></script>
<script src="<?php echo assets_url('assets_2/js/main.js'); ?>"></script>
<script src="<?php echo assets_url('assets/js/validation.js'); ?>"></script>